# Generated by Django 6.0.4 on 2026-04-16 07:19

import executions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_input_filename', models.CharField(max_length=255)),
                ('original_output_filename', models.CharField(blank=True, max_length=255)),
                ('input_file', models.FileField(upload_to=executions.models.input_upload_path)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=executions.models.output_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('output_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
